### ISSUE TITLE
RubyDNS 2.0.0 available

### ISSUE THREAD

**Issue by ioquatix** [codenize-tools/roadworker#50]
This update is a big improvement to stability, if you have time to try it out and report any issues that would be great.

**Comment by ioquatix** [comment]
Just touching base on this, let me know if you have time to review.

**Comment by winebarrel** [comment]
hanks for letting me know :-)
Sorry for reply late...
I will update the gem version :smiley:

**Comment by ioquatix** [comment]
Great. There are some big changes happening right now, it's still unstable, but it would be great if, initially, you could try testing it.

**Comment by ioquatix** [comment]
I think this function here will be simplified, as no longer depend on EventMachine global state.

https://github.com/codenize-tools/roadworker/blob/493035d624535ba1fbc98cc18154a7ccb7c1f1a1/spec/spec_helper.rb#L44

I can provide some ideas how to implement. But I don't have time at this very moment. Can you take a look, if you have time. It would be great to get some feedback.

**Comment by winebarrel** [comment]
Thanks!
I try to improve function.

**Comment by ioquatix** [comment]
Okay, rc2 is released, it's good to test.

**Comment by ioquatix** [comment]
RubyDNS 2.0.0 was released. Please consider updating and let me know any feedback. Thanks.

**Comment by winebarrel** [comment]
Fix to now use dnsruby
