### ISSUE TITLE
[Proposal] Ruby2.4 support

### ISSUE THREAD

**Issue by k-oguma** [codenize-tools/roadworker#61]
Hi, Roadworker developers.

I'm Oguma.

Thank you for your gem of this.
I'm the following proposal for ruby 2.4 support.

### Proposal

Would you stop using net-dns on which roadworker depends?
https://github.com/codenize-tools/roadworker/blob/master/roadworker.gemspec#L24

### Motive

I discover problems at dependency gem the by including it.

ex)
```
/Users/k-oguma/work/repos/mercari-dns/vendor/bundle/ruby/2.4.0/gems/net-dns2-0.8.7/lib/net/dns/rr/classes.rb:35: warning : constant :: Fixnum is deprecated
```

- Workaround
   - Doesn't use Fixnum with net-dns2 
      - Fixnum to Integer at the Ruby 2.4 later.
      - ex) Like the following commit.
          - https://github.com/bluemonk/net-dns/pull/75

#### Problems

This gem is following Authors, the administrator of this gem in the Rubygem cannot find out no matter how much it searches.
https://github.com/kouzoh/net-dns3#authors-original-net-dns2

Also, I think this author can not resurrect net-dns to Rubygem.

The following two authors's Github users etc were found.

Mr. @weppos
https://github.com/weppos
https://twitter.com/weppos

^ But it seems not to be involved in net-dns anymore

Mr. @bluemonk
https://github.com/bluemonk

^ He is out of communication.
Recent activity on Github also could not be seen.

Thank you.

**Comment by winebarrel** [comment]
Fix to use dnsruby

**Comment by itkq** [comment]
I think https://github.com/codenize-tools/roadworker/pull/67 resolved this issue, closing
