### ISSUE TITLE
Feature Request: Changelog

### ISSUE THREAD

**Issue by tsupertramp** [codenize-tools/roadworker#78]
Hey there,

using your tool since some years and really in love with it. It is fast and save and never caused any problems. Due to our high amount of DNS records we are not able to use terraform as it is slow and we would not see if any new records were created through API. It fits our need perfectly.

Every release makes me happy.

Could you add a CHANGELOG file, so i can quickly see the new features without going through PRs and commits?

Thanks a lot for all of your work and Greetings, Thomas

**Comment by itkq** [comment]
Hi @tsupertramp, thank you for the feedback.
I think that's a good idea. I quickly created CHANGELOG.md with a notice from README.md and recent changes in https://github.com/codenize-tools/roadworker/pull/80. I will add a changelog when releasing a new version.
